### PR TITLE
Add farfield to DoubleLayerRotatedMW3D

### PR DESCRIPTION
**Pull request by djukic14**
Hello,

I added a new struct to be able to calculate the farfield of DoubleLayerRotatedMW3D. The new struct is called MWDoubleLayerRotatedFarField3D.

### CODE REVIEW

**Comment by krcools** [comment]
This looks okay, but do we really need a factor waveimpedance in the double layer and rotated double layer far field? The double layer potential does not contain such a factor, so why would the far field do? Also setting it to 1.0 by default makes some assumptions on the precision and realness a user is using...

**Comment by krcools** [comment]
Another idea could be to implement `\times` by `BEAST.n` to automatically make a rotated double layer from a double layer and vice versa.

**Comment by djukic14** [comment]
> This looks okay, but do we really need a factor waveimpedance in the double layer and rotated double layer far field? The double layer potential does not contain such a factor, so why would the far field do? Also setting it to 1.0 by default makes some assumptions on the precision and realness a user is using...

If we opt to retain the wave impedance, we can determine its type from gamma's type. This keeps a consistency between the double layer far field structs and the single layer far field struct, but I can remove the wave impedance as well.

**Comment by krcools** [comment]
Maybe just rename it to amplitude. This makes the code reusable beyond the context of Maxwell3D. Even within Maxwell3D it does not have the meaning of an impedance, as studying the dimensions will reveal.

**Comment by djukic14** [comment]
I renamed waveimpedance to amplitude and added to cross functions

**Pull request merged**
